from langchain_community.document_loaders import WebBaseLoader
from bs4 import SoupStrainer

fastapi_documents = [
    "https://fastapi.tiangolo.com/python-types/",
    "https://fastapi.tiangolo.com/async/",
    "https://fastapi.tiangolo.com/environment-variables/",
    "https://fastapi.tiangolo.com/virtual-environments/",
    "https://fastapi.tiangolo.com/tutorial/",
    "https://fastapi.tiangolo.com/tutorial/first-steps/",
    "https://fastapi.tiangolo.com/tutorial/path-params/",
    "https://fastapi.tiangolo.com/tutorial/query-params/",
    "https://fastapi.tiangolo.com/tutorial/body/",
    "https://fastapi.tiangolo.com/tutorial/query-params-str-validations/",
    "https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/",
    "https://fastapi.tiangolo.com/tutorial/query-param-models/",
    "https://fastapi.tiangolo.com/tutorial/body-multiple-params/",
    "https://fastapi.tiangolo.com/tutorial/body-fields/",
    "https://fastapi.tiangolo.com/tutorial/body-nested-models/",
    "https://fastapi.tiangolo.com/tutorial/schema-extra-example/",
    "https://fastapi.tiangolo.com/tutorial/extra-data-types/",
    "https://fastapi.tiangolo.com/tutorial/cookie-params/",
    "https://fastapi.tiangolo.com/tutorial/header-params/",
    "https://fastapi.tiangolo.com/tutorial/cookie-param-models/",
    "https://fastapi.tiangolo.com/tutorial/header-param-models/",
    "https://fastapi.tiangolo.com/tutorial/response-model/",
    "https://fastapi.tiangolo.com/tutorial/extra-models/",
    "https://fastapi.tiangolo.com/tutorial/response-status-code/",
    "https://fastapi.tiangolo.com/tutorial/request-forms/",
    "https://fastapi.tiangolo.com/tutorial/request-form-models/",
    "https://fastapi.tiangolo.com/tutorial/request-files/",
    "https://fastapi.tiangolo.com/tutorial/request-forms-and-files/",
    "https://fastapi.tiangolo.com/tutorial/handling-errors/",
    "https://fastapi.tiangolo.com/tutorial/path-operation-configuration/",
    "https://fastapi.tiangolo.com/tutorial/encoder/",
    "https://fastapi.tiangolo.com/tutorial/body-updates/",
    "https://fastapi.tiangolo.com/tutorial/dependencies/",
    "https://fastapi.tiangolo.com/tutorial/dependencies/classes-as-dependencies/",
    "https://fastapi.tiangolo.com/tutorial/dependencies/sub-dependencies/",
    "https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-in-path-operation-decorators/",
    "https://fastapi.tiangolo.com/tutorial/dependencies/global-dependencies/",
    "https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/",
    "https://fastapi.tiangolo.com/tutorial/security/",
    "https://fastapi.tiangolo.com/tutorial/security/first-steps/",
    "https://fastapi.tiangolo.com/tutorial/security/get-current-user/",
    "https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/",
    "https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/",
    "https://fastapi.tiangolo.com/tutorial/middleware/",
    "https://fastapi.tiangolo.com/tutorial/cors/",
    "https://fastapi.tiangolo.com/tutorial/sql-databases/",
    "https://fastapi.tiangolo.com/tutorial/bigger-applications/",
    "https://fastapi.tiangolo.com/tutorial/background-tasks/",
    "https://fastapi.tiangolo.com/tutorial/metadata/",
    "https://fastapi.tiangolo.com/tutorial/static-files/",
    "https://fastapi.tiangolo.com/tutorial/testing/",
    "https://fastapi.tiangolo.com/tutorial/debugging/",
    "https://fastapi.tiangolo.com/advanced/",
    "https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/",
    "https://fastapi.tiangolo.com/advanced/additional-status-codes/",
    "https://fastapi.tiangolo.com/advanced/response-directly/",
    "https://fastapi.tiangolo.com/advanced/custom-response/",
    "https://fastapi.tiangolo.com/advanced/additional-responses/",
    "https://fastapi.tiangolo.com/advanced/response-cookies/",
    "https://fastapi.tiangolo.com/advanced/response-headers/",
    "https://fastapi.tiangolo.com/advanced/response-change-status-code/",
    "https://fastapi.tiangolo.com/advanced/advanced-dependencies/",
    "https://fastapi.tiangolo.com/advanced/security/",
    "https://fastapi.tiangolo.com/advanced/security/oauth2-scopes/",
    "https://fastapi.tiangolo.com/advanced/security/http-basic-auth/",
    "https://fastapi.tiangolo.com/advanced/using-request-directly/",
    "https://fastapi.tiangolo.com/advanced/dataclasses/",
    "https://fastapi.tiangolo.com/advanced/middleware/",
    "https://fastapi.tiangolo.com/advanced/sub-applications/",
    "https://fastapi.tiangolo.com/advanced/behind-a-proxy/",
    "https://fastapi.tiangolo.com/advanced/templates/",
    "https://fastapi.tiangolo.com/advanced/websockets/",
    "https://fastapi.tiangolo.com/advanced/events/",
    "https://fastapi.tiangolo.com/advanced/testing-websockets/",
    "https://fastapi.tiangolo.com/advanced/testing-events/",
    "https://fastapi.tiangolo.com/advanced/testing-dependencies/",
    "https://fastapi.tiangolo.com/advanced/async-tests/",
    "https://fastapi.tiangolo.com/advanced/settings/",
    "https://fastapi.tiangolo.com/advanced/openapi-callbacks/",
    "https://fastapi.tiangolo.com/advanced/openapi-webhooks/",
    "https://fastapi.tiangolo.com/advanced/wsgi/",
    "https://fastapi.tiangolo.com/advanced/generate-clients/",
    "https://fastapi.tiangolo.com/fastapi-cli/",
    "https://fastapi.tiangolo.com/deployment/",
    "https://fastapi.tiangolo.com/deployment/versions/",
    "https://fastapi.tiangolo.com/deployment/fastapicloud/",
    "https://fastapi.tiangolo.com/deployment/https/",
    "https://fastapi.tiangolo.com/deployment/manually/",
    "https://fastapi.tiangolo.com/deployment/concepts/",
    "https://fastapi.tiangolo.com/deployment/cloud/",
    "https://fastapi.tiangolo.com/deployment/server-workers/",
    "https://fastapi.tiangolo.com/deployment/docker/",
    "https://fastapi.tiangolo.com/how-to/",
    "https://fastapi.tiangolo.com/how-to/general/",
    "https://fastapi.tiangolo.com/how-to/migrate-from-pydantic-v1-to-pydantic-v2/",
    "https://fastapi.tiangolo.com/how-to/graphql/",
    "https://fastapi.tiangolo.com/how-to/custom-request-and-route/",
    "https://fastapi.tiangolo.com/how-to/conditional-openapi/",
    "https://fastapi.tiangolo.com/how-to/extending-openapi/",
    "https://fastapi.tiangolo.com/how-to/separate-openapi-schemas/",
    "https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/",
    "https://fastapi.tiangolo.com/how-to/configure-swagger-ui/",
    "https://fastapi.tiangolo.com/how-to/testing-database/",
    "https://fastapi.tiangolo.com/how-to/authentication-error-status-code/",
]

fastapi_documents_in_topics = {
    "python-types": ["https://fastapi.tiangolo.com/python-types/"],
    "async": ["https://fastapi.tiangolo.com/async/"],
    "environment-variables": ["https://fastapi.tiangolo.com/environment-variables/"],
    "virtual-environments": ["https://fastapi.tiangolo.com/virtual-environments/"],
    "tutorial": [
        "https://fastapi.tiangolo.com/tutorial/",
        "https://fastapi.tiangolo.com/tutorial/first-steps/",
        "https://fastapi.tiangolo.com/tutorial/path-params/",
        "https://fastapi.tiangolo.com/tutorial/query-params/",
        "https://fastapi.tiangolo.com/tutorial/body/",
        "https://fastapi.tiangolo.com/tutorial/query-params-str-validations/",
        "https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/",
        "https://fastapi.tiangolo.com/tutorial/query-param-models/",
        "https://fastapi.tiangolo.com/tutorial/body-multiple-params/",
        "https://fastapi.tiangolo.com/tutorial/body-fields/",
        "https://fastapi.tiangolo.com/tutorial/body-nested-models/",
        "https://fastapi.tiangolo.com/tutorial/schema-extra-example/",
        "https://fastapi.tiangolo.com/tutorial/extra-data-types/",
        "https://fastapi.tiangolo.com/tutorial/cookie-params/",
        "https://fastapi.tiangolo.com/tutorial/header-params/",
        "https://fastapi.tiangolo.com/tutorial/cookie-param-models/",
        "https://fastapi.tiangolo.com/tutorial/header-param-models/",
        "https://fastapi.tiangolo.com/tutorial/response-model/",
        "https://fastapi.tiangolo.com/tutorial/extra-models/",
        "https://fastapi.tiangolo.com/tutorial/response-status-code/",
        "https://fastapi.tiangolo.com/tutorial/request-forms/",
        "https://fastapi.tiangolo.com/tutorial/request-form-models/",
        "https://fastapi.tiangolo.com/tutorial/request-files/",
        "https://fastapi.tiangolo.com/tutorial/request-forms-and-files/",
        "https://fastapi.tiangolo.com/tutorial/handling-errors/",
        "https://fastapi.tiangolo.com/tutorial/path-operation-configuration/",
        "https://fastapi.tiangolo.com/tutorial/encoder/",
        "https://fastapi.tiangolo.com/tutorial/body-updates/",
        "https://fastapi.tiangolo.com/tutorial/dependencies/",
        "https://fastapi.tiangolo.com/tutorial/dependencies/classes-as-dependencies/",
        "https://fastapi.tiangolo.com/tutorial/dependencies/sub-dependencies/",
        "https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-in-path-operation-decorators/",
        "https://fastapi.tiangolo.com/tutorial/dependencies/global-dependencies/",
        "https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/",
        "https://fastapi.tiangolo.com/tutorial/security/",
        "https://fastapi.tiangolo.com/tutorial/security/first-steps/",
        "https://fastapi.tiangolo.com/tutorial/security/get-current-user/",
        "https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/",
        "https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/",
        "https://fastapi.tiangolo.com/tutorial/middleware/",
        "https://fastapi.tiangolo.com/tutorial/cors/",
        "https://fastapi.tiangolo.com/tutorial/sql-databases/",
        "https://fastapi.tiangolo.com/tutorial/bigger-applications/",
        "https://fastapi.tiangolo.com/tutorial/background-tasks/",
        "https://fastapi.tiangolo.com/tutorial/metadata/",
        "https://fastapi.tiangolo.com/tutorial/static-files/",
        "https://fastapi.tiangolo.com/tutorial/testing/",
        "https://fastapi.tiangolo.com/tutorial/debugging/",
    ],
    "advanced": [
        "https://fastapi.tiangolo.com/advanced/",
        "https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/",
        "https://fastapi.tiangolo.com/advanced/additional-status-codes/",
        "https://fastapi.tiangolo.com/advanced/response-directly/",
        "https://fastapi.tiangolo.com/advanced/custom-response/",
        "https://fastapi.tiangolo.com/advanced/additional-responses/",
        "https://fastapi.tiangolo.com/advanced/response-cookies/",
        "https://fastapi.tiangolo.com/advanced/response-headers/",
        "https://fastapi.tiangolo.com/advanced/response-change-status-code/",
        "https://fastapi.tiangolo.com/advanced/advanced-dependencies/",
        "https://fastapi.tiangolo.com/advanced/security/",
        "https://fastapi.tiangolo.com/advanced/security/oauth2-scopes/",
        "https://fastapi.tiangolo.com/advanced/security/http-basic-auth/",
        "https://fastapi.tiangolo.com/advanced/using-request-directly/",
        "https://fastapi.tiangolo.com/advanced/dataclasses/",
        "https://fastapi.tiangolo.com/advanced/middleware/",
        "https://fastapi.tiangolo.com/advanced/sub-applications/",
        "https://fastapi.tiangolo.com/advanced/behind-a-proxy/",
        "https://fastapi.tiangolo.com/advanced/templates/",
        "https://fastapi.tiangolo.com/advanced/websockets/",
        "https://fastapi.tiangolo.com/advanced/events/",
        "https://fastapi.tiangolo.com/advanced/testing-websockets/",
        "https://fastapi.tiangolo.com/advanced/testing-events/",
        "https://fastapi.tiangolo.com/advanced/testing-dependencies/",
        "https://fastapi.tiangolo.com/advanced/async-tests/",
        "https://fastapi.tiangolo.com/advanced/settings/",
        "https://fastapi.tiangolo.com/advanced/openapi-callbacks/",
        "https://fastapi.tiangolo.com/advanced/openapi-webhooks/",
        "https://fastapi.tiangolo.com/advanced/wsgi/",
        "https://fastapi.tiangolo.com/advanced/generate-clients/",
    ],
    "fastapi-cli": ["https://fastapi.tiangolo.com/fastapi-cli/"],
    "deployment": [
        "https://fastapi.tiangolo.com/deployment/",
        "https://fastapi.tiangolo.com/deployment/versions/",
        "https://fastapi.tiangolo.com/deployment/fastapicloud/",
        "https://fastapi.tiangolo.com/deployment/https/",
        "https://fastapi.tiangolo.com/deployment/manually/",
        "https://fastapi.tiangolo.com/deployment/concepts/",
        "https://fastapi.tiangolo.com/deployment/cloud/",
        "https://fastapi.tiangolo.com/deployment/server-workers/",
        "https://fastapi.tiangolo.com/deployment/docker/",
    ],
    "how-to": [
        "https://fastapi.tiangolo.com/how-to/",
        "https://fastapi.tiangolo.com/how-to/general/",
        "https://fastapi.tiangolo.com/how-to/migrate-from-pydantic-v1-to-pydantic-v2/",
        "https://fastapi.tiangolo.com/how-to/graphql/",
        "https://fastapi.tiangolo.com/how-to/custom-request-and-route/",
        "https://fastapi.tiangolo.com/how-to/conditional-openapi/",
        "https://fastapi.tiangolo.com/how-to/extending-openapi/",
        "https://fastapi.tiangolo.com/how-to/separate-openapi-schemas/",
        "https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/",
        "https://fastapi.tiangolo.com/how-to/configure-swagger-ui/",
        "https://fastapi.tiangolo.com/how-to/testing-database/",
        "https://fastapi.tiangolo.com/how-to/authentication-error-status-code/",
    ],
}

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15",
}

bs4_strainer = SoupStrainer("article", class_="md-content__inner md-typeset")

documents = WebBaseLoader(
    web_path=fastapi_documents,
    bs_kwargs={
        "parse_only": bs4_strainer,
    },
    header_template=headers,
).load()

import pickle

# dump documents to file fastapi_documents.pkl

with open("fastapi_documents.pkl", "wb") as f:
    pickle.dump(documents, f)

pass
